<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_quickcontent
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

// no direct access
defined('_JEXEC') or die;



// Init some API objects
// ================================================================================
$app 	= JFactory::getApplication() ;
$date 	= JFactory::getDate( 'now' , JFactory::getConfig()->get('offset') ) ;
$doc 	= JFactory::getDocument();
$uri 	= JFactory::getURI() ;
$user	= JFactory::getUser();
$userId	= $user->get('id');



// List Control
// ================================================================================
$listOrder	= $this->state->get('list.ordering');
$listDirn	= $this->state->get('list.direction');
$canOrder	= $user->authorise('core.edit.state', 'com_quickcontent');
$saveOrder	= $listOrder == 'a.ordering' || ($listOrder == 'a.lft' && $listDirn == 'asc');
$trashed	= $this->state->get('filter.published') == -2 ? true : false;
$nested		= $this->state->get('items.nested') ;
$orderCol 	= $nested ? 'a.lft' : 'a.ordering' ;
$show_root	= JRequest::getVar('show_root') ;


// For Joomla!3.0
// ================================================================================
if( JVERSION >= 3 ) {
	if ($saveOrder)
	{
		$method = $nested ? 'saveOrderNestedAjax' : 'saveOrderAjax' ;
		$saveOrderingUrl = 'index.php?option=com_quickcontent&task=lists.'.$method.'&tmpl=component';
		JHtml::_('sortablelist.sortable', 'itemList', 'adminForm', strtolower($listDirn), $saveOrderingUrl, false, $nested);
	}
}
?>

<!-- List Table -->
<table class="table table-striped adminlist" id="itemList">
	<thead>
		<tr>
			<?php if( JVERSION >= 3 ): ?>
			<th width="1%" class="nowrap center hidden-phone">
				<?php echo JHtml::_('grid.sort', '<i class="icon-menu-2"></i>', $orderCol, $listDirn, $listOrder, null, 'asc', 'JGRID_HEADING_ORDERING'); ?>
			</th>
			<?php endif; ?>
			
			<th width="1%">
				<input type="checkbox" name="checkall-toggle" value="" onclick="Joomla.checkAll(this)" />
			</th>
			
			<th width="15%">
				<?php echo JHtml::_('grid.sort',  'JGLOBAL_TITLE', 'a.title', $listDirn, $listOrder); ?>
			</th>
			
			<th width="7%" class='left' class="nowrap">
			<?php echo JHtml::_('grid.sort',  'COM_QUICKCONTENT_MENUTYPE', 'a.menutype', $listDirn, $listOrder); ?>
			</th>
			<th width="7%" class='left' class="nowrap">
			<?php echo JHtml::_('grid.sort',  'COM_QUICKCONTENT_VIEWTYPE', 'a.category_menutype', $listDirn, $listOrder); ?>
			</th>
			<th width="7%" class='left' class="nowrap">
			<?php echo JHtml::_('grid.sort',  'COM_QUICKCONTENT_CLEARMENU', 'a.delete_existing', $listDirn, $listOrder); ?>
			</th>
			<th class='left'>
			<?php echo JHtml::_('grid.sort',  'COM_QUICKCONTENT_LIST_CONTENT', 'a.content', $listDirn, $listOrder); ?>
			</th>
			
			<th>
				<?php echo JText::_('COM_QUICKCONTENT_GENERATE_NOW'); ?>
			</th>
			<th>
				<?php echo JText::_('COM_QUICKCONTENT_RESTORE'); ?>
			</th>
			
			<!--<th width="5%" class="nowrap">
				<?php echo JHtml::_('grid.sort',  'JPUBLISHED', 'a.published', $listDirn, $listOrder); ?>
			</th>-->
			
			<?php if( JVERSION < 3 ): ?>
			<th width="10%">
				<?php echo JHtml::_('grid.sort',  'JGRID_HEADING_ORDERING', $orderCol, $listDirn, $listOrder); ?>
				<?php if ($canOrder && $saveOrder) :?>
					<?php echo JHtml::_('grid.order',  $this->items, 'filesave.png', 'lists.saveorder'); ?>
				<?php endif; ?>
			</th>
			<?php endif; ?>
			
			
			<th width="1%" class="nowrap">
				<?php echo JHtml::_('grid.sort',  'JGRID_HEADING_ID', 'a.id', $listDirn, $listOrder); ?>
			</th>

		</tr>
	</thead>
	<tfoot>
		<tr>
			<td colspan="15">
				<div class="pull-left">
					<?php echo $this->pagination->getListFooter(); ?>
				</div>
				
				<?php if( JVERSION >= 3 ): ?>
				<!-- Limit Box -->
				<div class="btn-group pull-right hidden-phone">
					<label for="limit" class="element-invisible"><?php echo JText::_('JFIELD_PLG_SEARCH_SEARCHLIMIT_DESC');?></label>
					<?php echo $this->pagination->getLimitBox(); ?>
				</div>
				<?php endif; ?>
			</td>
		</tr>
	</tfoot>
	<tbody>
	<?php foreach ($this->items as $i => $item) :
		
		$item = new JObject($item);
		
		$ordering	= ($listOrder == $orderCol);
		$canEdit	= $user->authorise('core.edit',			'com_quickcontent.list.'.$item->a_id);
		$canCheckin	= $user->authorise('core.manage',		'com_quickcontent.list.'.$item->a_id) || $item->a_checked_out == $userId || $item->a_checked_out == 0;
		$canChange	= $user->authorise('core.edit.state',	'com_quickcontent.list.'.$item->a_id) && $canCheckin;
		$canEditOwn = $user->authorise('core.edit.own',		'com_quickcontent.list.'.$item->a_id) && $item->c_id == $userId;

		?>
		<tr class="row<?php echo $i % 2; ?>"
			<?php if( $nested ): ?>
				sortable-group-id="<?php echo $item->a_parent_id ;?>" item-id="<?php echo $item->a_id?>" parents="<?php echo $parentsStr?>" level="<?php echo $item->a_level?>"
			<?php else: ?>
				sortable-group-id="<?php echo $item->a_catid ;?>"
			<?php endif; ?>
		>
		<?php if( JVERSION >= 3 ): ?>
			<!-- Drag sort for Joomla!3.0 -->
			<td class="order nowrap center hidden-phone">
			<?php if ($canChange) :
				$disableClassName = '';
				$disabledLabel	  = '';

				if (!$saveOrder) :
					$disabledLabel    = JText::_('JORDERINGDISABLED');
					$disableClassName = 'inactive tip-top';
				endif; ?>
				<span class="sortable-handler hasTooltip <?php echo $disableClassName?>" title="<?php echo $disabledLabel?>">
					<i class="icon-menu"></i>
				</span>
				<input type="text" style="display:none" name="order[]" size="5" value="<?php echo $nested ? $orderkey + 1 : $item->a_ordering;?>" class="width-20 text-area-order " />
			<?php else : ?>
				<span class="sortable-handler inactive" >
					<i class="icon-menu"></i>
				</span>
			<?php endif; ?>
			</td>
		<?php endif; ?>
		
			<td class="center">
				<?php echo JHtml::_('grid.id', $i, $item->a_id); ?>
			</td>
			
			<td class="n/owrap has-context">
				<!-- Nested dashs -->
				<?php if( $nested ): ?>
				<div class="pull-left fltlft">
					<?php $offset = $show_root ? 0 : 1 ; ?>
					<?php echo str_repeat('<span class="gi">&mdash;</span>', $item->a_level - $offset) ; ?>
				</div>
				<?php endif; ?>
				
				<div class="pull-left fltlft">
				
				
				<!-- Checkout -->
				<?php if ($item->get('a_checked_out')) : ?>
					<?php echo JHtml::_('jgrid.checkedout', $i, $item->get('a_checked_out'), $item->get('a_checked_out_time'), 'lists.', $canCheckin); ?>
				<?php endif; ?>
				
				
				<!-- Title -->
				<?php if ($canEdit || $canEditOwn) : ?>
					<a href="<?php echo JRoute::_('index.php?option=com_quickcontent&task=list.edit&id='.$item->a_id); ?>">
						<?php echo $item->get('a_title'); ?>
					</a>
				<?php else: ?>
					<?php echo $item->get('a_title'); ?>
				<?php endif; ?>
				
			</td>
			
			<td>
					<?php echo $item->a_menutype ; ?>
				</td>
				<td>
					<?php 
					switch($item->category_menutype ){
						case 'list' : echo JText::_('COM_QUICKCONTENT_VIEW_LIST') ;		break;
						case 'blog' : echo JText::_('COM_QUICKCONTENT_VIEW_BLOG') ;		break;
						default 	: echo JText::_('COM_QUICKCONTENT_VIEW_NONE') ;		break;
					}
					?>
				</td>
				<td>
					<?php 
						if($item->delete_existing)
							echo JText::_('JYES') ;
						else
							echo JText::_('JNO'); 
					?>
				</td>
				<td>
					<?php echo JString::substr( strip_tags($item->content) , 0 , 150 ).'...'; ?>
				</td>
				

				<td class="center">
					<?php $generated = $item->a_generated; ?>
					<?php $disabled_bg = $generated ? 'background-position: 0 32px;' : ''; ?>
					<span >
						<a style="<?php echo JVERSION < 3 ? 'width:32px;height:32px;text-indent:-5000px;display:inline-block;background:url(templates/bluestork/images/toolbar/icon-32-new.png);'.$disabled_bg : '' ; ?>"
							<?php if( $generated ): ?>
							href="javascript:void(0);"
							<?php else: ?>
							href="index.php?option=com_quickcontent&task=generator.generate&id=<?php echo $item->a_id ?>"
							<?php endif; ?>
							class="btn btn-primary <?php echo (JVERSION >= 3 && $generated) ? 'disabled' : ''; ?>">
							<i class="icon-new icon-white"></i>
						</a>
					</span>
				</td>
				
				<td class="center">
					<span >
						<a style="<?php echo JVERSION < 3 ? 'width:32px;height:32px;text-indent:-5000px;display:inline-block;background:url(templates/bluestork/images/toolbar/icon-32-refresh.png);' : '' ; ?>" 
						href="index.php?option=com_quickcontent&task=generator.restore&id=<?php echo $item->a_id ?>"
						class="btn btn-danger">
						<i class="icon-refresh iconwhite"></i></a>
					</span>
				</td>
			
			<!--<td class="center">
				<?php echo JHtml::_('jgrid.published', $item->a_published, $i, 'lists.', $canChange, 'cb', $item->a_publish_up, $item->a_publish_down); ?>
			</td>-->
			
			<?php if( JVERSION < 3 ): ?>
			<td class="order">
				<?php if ($canChange) : ?>
					<?php if ($saveOrder) :?>
						<?php if ($listDirn == 'asc') : ?>
							<span><?php echo $this->pagination->orderUpIcon($i, true, 'lists.orderup', 'JLIB_HTML_MOVE_UP', $ordering); ?></span>
							<span><?php echo $this->pagination->orderDownIcon($i, $this->pagination->total, true, 'lists.orderdown', 'JLIB_HTML_MOVE_DOWN', $ordering); ?></span>
						<?php elseif ($listDirn == 'desc') : ?>
							<span><?php echo $this->pagination->orderUpIcon($i, true, 'lists.orderdown', 'JLIB_HTML_MOVE_UP', $ordering); ?></span>
							<span><?php echo $this->pagination->orderDownIcon($i, $this->pagination->total, true, 'lists.orderup', 'JLIB_HTML_MOVE_DOWN', $ordering); ?></span>
						<?php endif; ?>
					<?php endif; ?>
					<?php $disabled = $saveOrder ?  '' : 'disabled="disabled"'; ?>
					<input type="text" name="order[]" size="5" value="<?php echo $nested ? $orderkey + 1 : $item->get('a_ordering');?>" <?php echo $disabled ?> class="text-area-order input-mini" />
				<?php else : ?>
					<?php echo $nested ? $orderkey + 1 : $item->get('a_ordering');?>
				<?php endif; ?>
			</td>
			<?php endif; ?>
			

			<td class="center">
				<span
					<?php if( $nested ): ?>
					class="hasTip" title="<?php echo $item->a_lft.'-'.$item->a_rgt; ?>"
					<?php endif; ?>
				><?php echo (int) $item->get('a_id'); ?></span>
			</td>

		</tr>
		<?php endforeach; ?>
	</tbody>
</table>