<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_quickcontent
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

// no direct access
defined('_JEXEC') or die;

include_once AKPATH_COMPONENT.'/viewlist.php' ;

/**
 * View class for a list of Quickcontent.
 */
class QuickcontentViewLists extends AKViewList
{
	/**
	 * @var		string	The prefix to use with controller messages.
	 * @since	1.6
	 */
	protected 	$text_prefix = 'COM_QUICKCONTENT';
	protected 	$items;
	protected 	$pagination;
	protected 	$state;
	
	public		$option 	= 'com_quickcontent' ;
	public		$list_name 	= 'lists' ;
	public		$item_name 	= 'list' ;
	public		$sort_fields ;

	
	
	/**
	 * Display the view
	 */
	public function display($tpl = null)
	{
		$app = JFactory::getApplication() ;
		
		$this->state		= $this->get('State');
		$this->items		= $this->get('Items');
		$this->pagination	= $this->get('Pagination');
		$this->filter		= $this->get('Filter');

		// Check for errors.
		if (count($errors = $this->get('Errors'))) {
			JError::raiseError(500, implode("\n", $errors));
			return false;
		}
		
		foreach( $this->items as &$item ):
			$item->a_params = new JRegistry($item->a_params);
		endforeach;
		
		parent::displayWithPanel($tpl);
	}

	
	
	/**
	 * Add the page title and toolbar.
	 *
	 * @since	1.6
	 */
	protected function addToolbar()
	{
		// Set title.
		AKToolBarHelper::title( JText::_($this->text_prefix.'_TITLE_LIST'), 'article.png');
		
		$state	= $this->get('State');
		$canDo	= AKHelper::getActions($this->option);
		$user 	= JFactory::getUser() ;
		$filter_state 	= $this->state->get('filter') ;
		
        // Get the toolbar object instance
		$bar = JToolBar::getInstance('toolbar');
       
		
		// Toolbar Buttons
		// ========================================================================
		if ($canDo->get('core.create') || (count($user->getAuthorisedCategories($this->option, 'core.create'))) > 0 ) {
			JToolBarHelper::addNew( $this->item_name.'.add');
		}

		if ($canDo->get('core.edit')) {
			JToolBarHelper::editList( $this->item_name.'.edit');
		}

		if ($canDo->get('core.edit.state')) {
			JToolBarHelper::divider();
			JToolbarHelper::checkin($this->list_name.'.checkin');
			
			JToolBarHelper::divider();
		}
		

		JToolbarHelper::deleteList('Are you sure?', $this->list_name.'.delete');
		
		// Add a batch modal button
		if ($user->authorise('core.edit') && JVERSION >= 3)
		{
			AKToolbarHelper::modal( 'JTOOLBAR_BATCH', 'batchModal');
		}
		
		if ($canDo->get('core.admin')) {
			AKToolBarHelper::preferences($this->option);
		}
		
		$msg = JText::_('COM_QUICKCONTENT_CLEAR_WHOLE_SITE_ALERT') ;
		
		$bar = JToolBar::getInstance('toolbar');
		$bar->appendButton('Confirm', $msg, 'delete', 'COM_QUICKCONTENT_CLEAR_WHOLE_SITE', 'generator.deleteAll', false);
	}
	
	
	/**
	 * Returns an array of fields the table can be sorted by
	 *
	 * @return  array  Array containing the field name to sort by as the key and display text as value
	 *
	 * @since   3.0
	 */
	protected function getSortFields()
	{
		$ordering_key = $this->state->get('items.nested') ? 'a.lft' : 'a.ordering' ;
		
		$this->sort_fields = array(
			$ordering_key 		=> JText::_('JGRID_HEADING_ORDERING'),
			'a.title' 			=> JText::_('JGLOBAL_TITLE'),
			'a.menutype' 		=> JText::_('COM_QUICKCONTENT_MENUTYPE'),
			'a.category_menutype' 	=> JText::_('COM_QUICKCONTENT_VIEWTYPE'),
			'e.delete_existing' 	=> JText::_('COM_QUICKCONTENT_CLEARMENU'),
			'a.content' 		=> JText::_('COM_QUICKCONTENT_LIST_CONTENT'),
			'a.id' 				=> JText::_('JGRID_HEADING_ID')
		);
		
		return $this->sort_fields ;
	}
	
	
}
